import { ArrowRight, Compass, Heart, Search, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { StoreLayout } from "@/components/StoreLayout";
import { useReveal } from "@/hooks/useReveal";

export default function Story() {
  useReveal();
  return <StoreLayout><section className="story-page-hero"><div className="container-carmen story-page-intro"><span className="eyebrow">Carmen Antika / Hikâyemiz</span><h1>Eşya değil,<br /><em>iz</em> biriktiriyoruz.</h1><p>Antalya'nın farklı köşelerindeki bit pazarlarını, eski dükkânları ve unutulmuş çekmeceleri geziyoruz. Bazen bir radyo, bazen kurmalı bir oyuncak, bazen de ne işe yaradığını bilmediğimiz bir parça buluyoruz.</p></div></section><section className="story-page-grid container-carmen"><div className="story-page-image reveal-on-scroll" data-reveal><img src="/manus-storage/market-objects_9b5b96e4.jpeg" alt="Bit pazarında bulunan eski fotoğraf makineleri ve küçük objeler" /></div><div className="story-page-copy reveal-on-scroll" data-reveal style={{ "--reveal-delay": "120ms" } as React.CSSProperties}><span className="eyebrow">01 / Bulmak</span><h2>Gözden kaçanı<br /><em>görmek.</em></h2><p>Bizim için iyi bir parça kusursuz değil; kendinden önceki hayatını biraz belli eden parça. Tezgâhın kalabalığında, eski bir dükkânın rafında veya bir evin taşınma kolisinde karşılaşırız.</p><div className="story-pillars"><span><Compass size={16} /> Şehrin içinden</span><span><Search size={16} /> Araştırılmış</span><span><Heart size={16} /> Sevgiyle seçilmiş</span></div></div></section><section className="story-quote-band"><div className="container-carmen"><Sparkles size={20} /><blockquote>“İyi bulunan bir şey, sahibini de bulur.”</blockquote><span>Carmen'in defterinden</span></div></section><section className="story-page-cta"><div className="container-carmen"><span className="eyebrow">Sıradaki hikâye</span><h2>Belki bugün<br /><em>senin evindedir.</em></h2><Link className="primary-cta" href="/koleksiyon">Koleksiyona git <ArrowRight size={15} /></Link></div></section></StoreLayout>;
}
